services:
  nitro:
    image: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node:integration
    container_name: nitro-node
    ports:
      - "8547:8547"
      - "8548:8548"
      - "8549:8549"
    command: --conf.file /config/full_node.json
    volumes:
      - ./config:/config
      - ./wasm:/home/user/wasm/
      - ./database:/home/user/.arbitrum
    depends_on:
      - validation_node

  validation_node:
    image: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node:integration
    container_name: validation_node
    ports:
      - "8949:8549"
    volumes:
      - ./config:/config
    entrypoint: /usr/local/bin/nitro-val
    command: --conf.file /config/validation_node_config.json

  caff_node:
    image: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node@sha256:bf63374a00a5d6676ca39af79ac4b0f053128cb7438bcdaa746dba6656c12658
    container_name: caff_node
    ports:
      - "8550:8547"
      - "8551:8548"
      - "8552:8549"
    command: --conf.file /config/caff_node.json
    volumes:
      - ./caff-node/config:/config
      - ./caff-node/wasm:/home/user/wasm/
      - ./caff-node/database:/home/user/.arbitrum

  vrf-executor:
    image: vrf-executor:v0.0.1
    build:
      context: vrf-executor
      dockerfile: Dockerfile
    environment:
      - RPC=
      - PRIVATE_KEY=
      - VRF_CORE=
      - BLOCKS_INTERVAL=
      - CHAIN_ID=